version: 2

nightly:
  version_template: "{{ incpatch .Version }}-dev"
  tag_name: dev
  publish_release: true
  keep_single_release: true

builds:
  - id: cli
    main: ./cmd/cli/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: -s -w
    binary: ezcd-cli
  
  - id: server
    main: ./cmd/server/main.go
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags: -s -w
    binary: ezcd-server

dockers:
  - image_templates:
    - 'ghcr.io/ezcdlabs/ezcd-server:v{{ .Version }}'
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - server
archives:
  - id: cli
    builds:
      - cli
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"