version: 2

snapshot:
  version_template: "snapshot"

builds:
  - id: cli
    main: ./cmd/cli/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X main.version={{.Version}}
    binary: ezcd-cli
  
  - id: server
    main: ./cmd/server/main.go
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    binary: ezcd-server

dockers:
  - image_templates:
    - 'ghcr.io/ezcdlabs/ezcd-server:{{ if .IsSnapshot }}snapshot{{ else }}v{{ .Version }}{{ end }}'
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - server
archives:
  - id: cli
    builds:
      - cli
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"