name: "Setup EZCD CLI"
description: "Download and set up the EZCD CLI"
author: "EZCD Labs"
inputs:
  version:
    description: 'The version of the ezcd CLI to install'
    required: true
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Download ezcd CLI
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          version=$(curl -s https://api.github.com/repos/ezcdlabs/ezcd/releases/latest | jq -r .tag_name)
        else
          version=${{ inputs.version }}
        fi

        case ${{ runner.os }} in
          Linux) os=linux ;;
          macOS) os=darwin ;;
          Windows) os=windows ;;
          *) echo "Unsupported OS: ${{ runner.os }}" && exit 1 ;;
        esac

        case ${{ runner.arch }} in
          X64) arch=amd64 ;;
          ARM64) arch=arm64 ;;
          *) echo "Unsupported architecture: ${{ runner.arch }}" && exit 1 ;;
        esac

        url=https://github.com/ezcdlabs/ezcd/releases/download/$version/ezcd_${os}_${arch}.tar.gz
        echo "Downloading ezcd CLI version $version from $url"
        curl -L -o ezcdcli.tar.gz $url
        tar -xzf ezcdcli.tar.gz -C /usr/local/bin
    - name: Verify installation
      shell: bash
      run: ezcd-cli --version

