name: "Setup EZCD CLI"
description: "Download and set up the EZCD CLI"
author: "EZCD Labs"
inputs:
  version:
    description: 'The version of the ezcd CLI to install'
    required: true
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Download ezcd CLI
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          version=$(curl -s https://api.github.com/repos/ezcdlabs/ezcd/releases/latest | jq -r .tag_name)
        else
          version=${{ inputs.version }}
        fi

        url=https://github.com/ezcdlabs/ezcd/releases/download/$version/ezcd_${{ runner.os }}_${{ runner.arch }}.tar.gz
        echo "Downloading ezcd CLI version $version from $url"
        curl -L -o ezcdcli.tar.gz url
        tar -xzf ezcdcli.tar.gz -C /usr/local/bin
    - name: Verify installation
      shell: bash
      run: ezcd-cli --version