name: CI

on:
  push:
    branches:
      - main

jobs:
  build and release nightly:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.1'

    - name: Install dependencies
      run: make install

    - name: Run tests
      run: make test

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        version: latest
        args: release --clean --nightly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}