name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.1'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install dependencies
      run: make install

    - name: Build SolidJS frontend app
      run: make build-web

    - name: Run tests
      run: make test

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: ~> v2
        args: release --clean --snapshot 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Smoke test CLI
      run: ./dist/cli_linux_amd64_v1/ezcd-cli --version

    - name: Smoke test Server
      run: docker run ghcr.io/ezcdlabs/ezcd-server:snapshot --version