name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.1'

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Install dependencies
      run: make install

    - name: Run tests
      run: make test

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  smoke-test-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Setup EZCD CLI using github action
        uses: ezcdlabs/ezcd@main
        with:
          version: ${{ github.ref_name }}

      - name: Smoke test CLI
        run: ezcd-cli --version

  smoke-test-server:
    runs-on: ubuntu-latest
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Smoke test Server
        run: docker run --rm ghcr.io/ezcdlabs/ezcd:${{ github.ref_name }} --version