name: Smoke

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Setup EZCD CLI using github action
        uses: ezcdlabs/ezcd@main
        with:
          version: v0.1.11

      - name: Smoke test CLI
        run: ezcd-cli --version

      - name: Smoke test Server
        run: docker run --rm ghcr.io/ezcdlabs/ezcd:v0.1.11 --version